# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
env:
    global:
        # Set defaults to avoid repeating in most cases
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - CONDA_DEPENDENCIES='pytz'
        - PIP_DEPENDENCIES=''
        - SETUP_CMD='test -V'

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try MacOS X
        - os: osx
          env: PYTHON_VERSION=2.7
               CONDA_DEPENDENCIES='pytz matplotlib nose'
               PIP_DEPENDENCIES='pytest-mpl'

        # Check for sphinx doc build warnings - we do this first because it
        # runs for a long time. All dependencies are needed because the
        # plot_directive in sphinx needs them
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='build_sphinx -w'
               CONDA_DEPENDENCIES='pytz matplotlib nose wcsaxes astroquery'
               PIP_DEPENDENCIES='pytest-mpl'
        - os: linux
          env: PYTHON_VERSION=3.5 SETUP_CMD='build_sphinx -w'
               CONDA_DEPENDENCIES='pytz matplotlib nose wcsaxes astroquery'
               PIP_DEPENDENCIES='pytest-mpl'

        # Try all python versions with the latest numpy
        # TODO: add the `--open-files` option back once this issue has been resolved:
        # https://github.com/astropy/astroplan/pull/83#issuecomment-136129489
        - os: linux
          env: PYTHON_VERSION=2.7

        - os: linux
          env: PYTHON_VERSION=3.5

        # Now try with all optional dependencies on 2.7 and an appropriate 3.x
        # build (with latest numpy). We also note the code coverage on Python
        # 2.7.
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='test --remote-data -V --coverage'
               CONDA_DEPENDENCIES='pytz matplotlib nose'
               PIP_DEPENDENCIES='pytest-mpl'
        - os: linux
          env: PYTHON_VERSION=3.5 SETUP_CMD='test --remote-data -V'
               CONDA_DEPENDENCIES='pytz matplotlib nose'
               PIP_DEPENDENCIES='pytest-mpl'

        # Try older numpy versions
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.9
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.8
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.7

        # Try developer version of Numpy
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=dev

        # Try pre-release version of Numpy. This only runs if a pre-release
        # is available on pypi.
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=prerelease

        # Try developer version of Astropy
        - os: linux
          env: PYTHON_VERSION=2.7 ASTROPY_VERSION=dev

        # Do a PEP8 test with pycodestyle
        - os: linux
          env: PYTHON_VERSION=2.7 MAIN_CMD='pycodestyle astroplan --count' SETUP_CMD=''

    allow_failures:
      - env: PYTHON_VERSION=2.7 NUMPY_VERSION=dev
      # TODO: these fail for now ... make them work!
      - env: PYTHON_VERSION=2.7 MAIN_CMD='pycodestyle astroplan --count' SETUP_CMD=''
      # Allow them to fail now until the IERSs issues are fixed
      - env: PYTHON_VERSION=2.7 SETUP_CMD='test --remote-data -V --coverage'
             CONDA_DEPENDENCIES='pytz matplotlib nose'
             PIP_DEPENDENCIES='pytest-mpl'
      - env: PYTHON_VERSION=3.5 SETUP_CMD='test --remote-data -V'
             CONDA_DEPENDENCIES='pytz matplotlib nose'
             PIP_DEPENDENCIES='pytest-mpl'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

    # This is needed to make matplotlib plot testing work
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
          export DISPLAY=:99.0;
          sh -e /etc/init.d/xvfb start;
          export QT_API=pyqt;
      fi

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --remote-data -V --coverage' ]]; then
        coveralls --rcfile='astroplan/tests/coveragerc';
      fi
