# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      CONDA_DEPENDENCIES: "pytz matplotlib nose"
      PIP_DEPENDENCIES: "pyephem pytest-mpl"

  matrix:

      # Note that we don't support Python 2.6 in astroplan,
      # so we test Python 2.7 (whereas Astropy tests on 2.6)

      - PYTHON_VERSION: "2.7"
        NUMPY_VERSION: "stable"
        ASTROPY_VERSION: "stable"
      - PYTHON_VERSION: "3.5"
        NUMPY_VERSION: "stable"
        ASTROPY_VERSION: "stable"

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

# Not a .NET project, we build astroplan in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py test"
